In [1]:
import pandas as pd
import numpy as np

In [2]:
origin_df = pd.read_csv("train.csv")

In [3]:
origin_df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive

In [4]:
df = origin_df.loc[:, ['Id','GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice']]
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 18 columns):
Id               1460 non-null int64
GarageCond       1379 non-null object
PavedDrive       1460 non-null object
WoodDeckSF       1460 non-null int64
OpenPorchSF      1460 non-null int64
EnclosedPorch    1460 non-null int64
3SsnPorch        1460 non-null int64
ScreenPorch      1460 non-null int64
PoolArea         1460 non-null int64
PoolQC           7 non-null object
Fence            281 non-null object
MiscFeature      54 non-null object
MiscVal          1460 non-null int64
MoSold           1460 non-null int64
YrSold           1460 non-null int64
SaleType         1460 non-null object
SaleCondition    1460 non-null object
SalePrice        1460 non-null int64
dtypes: int64(11), object(7)
memory usage: 165.5+ KB


In [5]:
df.drop(columns=['PoolQC','MiscFeature','MoSold','YrSold','SaleType'], inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 13 columns):
Id               1460 non-null int64
GarageCond       1379 non-null object
PavedDrive       1460 non-null object
WoodDeckSF       1460 non-null int64
OpenPorchSF      1460 non-null int64
EnclosedPorch    1460 non-null int64
3SsnPorch        1460 non-null int64
ScreenPorch      1460 non-null int64
PoolArea         1460 non-null int64
Fence            281 non-null object
MiscVal          1460 non-null int64
SaleCondition    1460 non-null object
SalePrice        1460 non-null int64
dtypes: int64(9), object(4)
memory usage: 125.5+ KB


In [6]:
df.GarageCond.unique()

array(['TA', 'Fa', nan, 'Gd', 'Po', 'Ex'], dtype=object)

In [7]:
df.GarageCond.replace(to_replace=['Ex', 'Gd', 'TA', 'Fa', 'Po', np.nan], value=[5,4,3,2,1,0], inplace=True)
df.GarageCond.unique()

array([3, 2, 0, 4, 1, 5], dtype=int64)

In [8]:
df.PavedDrive.unique()

array(['Y', 'N', 'P'], dtype=object)

In [9]:
df.PavedDrive.replace(to_replace=['Y', 'N', 'P'], value=[2,0,1], inplace=True)
df.PavedDrive.unique()

array([2, 0, 1], dtype=int64)

In [10]:
df.PoolArea.unique()

array([  0, 512, 648, 576, 555, 480, 519, 738], dtype=int64)

In [11]:
pd.cut([512, 648, 576, 555, 480, 519, 738], 3)

[(479.742, 566.0], (566.0, 652.0], (566.0, 652.0], (479.742, 566.0], (479.742, 566.0], (479.742, 566.0], (652.0, 738.0]]
Categories (3, interval[float64]): [(479.742, 566.0] < (566.0, 652.0] < (652.0, 738.0]]

In [12]:
for area in df.PoolArea:
    if area!=0 and area<=566:
        df.PoolArea.replace(to_replace=area, value=1, inplace=True)
    elif area>566 and area<= 652:
        df.PoolArea.replace(to_replace=area, value=2, inplace=True)
    elif area >652:
        df.PoolArea.replace(to_replace=area, value=3, inplace=True)

In [13]:
df.PoolArea.unique()

array([0, 1, 2, 3], dtype=int64)

In [14]:
df.Fence.replace(to_replace=[np.nan, 'MnPrv', 'GdWo', 'GdPrv', 'MnWw'], value=[0,3,2,4,1], inplace=True)
df.Fence.unique()

array([0, 3, 2, 4, 1], dtype=int64)

In [15]:
added_columns=pd.get_dummies(df.SaleCondition,prefix='SC')
added_columns.columns

Index(['SC_Abnorml', 'SC_AdjLand', 'SC_Alloca', 'SC_Family', 'SC_Normal',
       'SC_Partial'],
      dtype='object')

In [16]:
df.drop(columns='SaleCondition')
SalePrice=df.SalePrice

In [17]:
df['SC_Abnorml']=added_columns['SC_Abnorml']
df['SC_AdjLand']=added_columns['SC_AdjLand']
df['SC_Alloca']=added_columns['SC_Alloca']
df['SC_Family']=added_columns['SC_Family']
df['SC_Normal']=added_columns['SC_Normal']
df['SC_Partial']=added_columns['SC_Partial']

In [18]:
df.drop(columns=['SaleCondition'], inplace=True)
df.head()

Id  GarageCond  PavedDrive  WoodDeckSF  OpenPorchSF  EnclosedPorch  \
0   1           3           2           0           61              0   
1   2           3           2         298            0              0   
2   3           3           2           0           42              0   
3   4           3           2           0           35            272   
4   5           3           2         192           84              0   

   3SsnPorch  ScreenPorch  PoolArea  Fence  MiscVal  SalePrice  SC_Abnorml  \
0          0            0         0      0        0     208500           0   
1          0            0         0      0        0     181500           0   
2          0            0         0      0        0     223500           0   
3          0            0         0      0        0     140000           1   
4          0            0         0      0        0     250000           0   

   SC_AdjLand  SC_Alloca  SC_Family  SC_Normal  SC_Partial  
0           0          0          0          1           0  
1           0          0          0          1           0  
2           0          0          0          1           0  
3           0          0          0          0           0  
4           0          0          0          1           0

In [19]:
df.drop(columns='SalePrice',inplace=True)
df['SalePrice']=SalePrice

In [20]:
df.head()

Id  GarageCond  PavedDrive  WoodDeckSF  OpenPorchSF  EnclosedPorch  \
0   1           3           2           0           61              0   
1   2           3           2         298            0              0   
2   3           3           2           0           42              0   
3   4           3           2           0           35            272   
4   5           3           2         192           84              0   

   3SsnPorch  ScreenPorch  PoolArea  Fence  MiscVal  SC_Abnorml  SC_AdjLand  \
0          0            0         0      0        0           0           0   
1          0            0         0      0        0           0           0   
2          0            0         0      0        0           0           0   
3          0            0         0      0        0           1           0   
4          0            0         0      0        0           0           0   

   SC_Alloca  SC_Family  SC_Normal  SC_Partial  SalePrice  
0          0          0          1           0     208500  
1          0          0          1           0     181500  
2          0          0          1           0     223500  
3          0          0          0           0     140000  
4          0          0          1           0     250000

In [21]:
df.to_csv('cleaned_BM_CB_train.csv',index=False)