In [1]:
import pandas as pd
import numpy as np

In [2]:
test_df = pd.read_csv("test.csv")

In [3]:
test_df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive

In [5]:
df = test_df.loc[:, ['Id','GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition']]
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 17 columns):
Id               1459 non-null int64
GarageCond       1381 non-null object
PavedDrive       1459 non-null object
WoodDeckSF       1459 non-null int64
OpenPorchSF      1459 non-null int64
EnclosedPorch    1459 non-null int64
3SsnPorch        1459 non-null int64
ScreenPorch      1459 non-null int64
PoolArea         1459 non-null int64
PoolQC           3 non-null object
Fence            290 non-null object
MiscFeature      51 non-null object
MiscVal          1459 non-null int64
MoSold           1459 non-null int64
YrSold           1459 non-null int64
SaleType         1458 non-null object
SaleCondition    1459 non-null object
dtypes: int64(10), object(7)
memory usage: 153.9+ KB


In [6]:
df.drop(columns=['PoolQC','MiscFeature','MoSold','YrSold','SaleType'], inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 12 columns):
Id               1459 non-null int64
GarageCond       1381 non-null object
PavedDrive       1459 non-null object
WoodDeckSF       1459 non-null int64
OpenPorchSF      1459 non-null int64
EnclosedPorch    1459 non-null int64
3SsnPorch        1459 non-null int64
ScreenPorch      1459 non-null int64
PoolArea         1459 non-null int64
Fence            290 non-null object
MiscVal          1459 non-null int64
SaleCondition    1459 non-null object
dtypes: int64(8), object(4)
memory usage: 114.0+ KB


In [7]:
df.GarageCond.replace(to_replace=['Ex', 'Gd', 'TA', 'Fa', 'Po', np.nan], value=[5,4,3,2,1,0], inplace=True)
df.GarageCond.unique()

array([3, 0, 2, 4, 1, 5], dtype=int64)

In [8]:
df.PavedDrive.replace(to_replace=['Y', 'N', 'P'], value=[2,0,1], inplace=True)
df.PavedDrive.unique()

array([2, 0, 1], dtype=int64)

In [9]:
df.PoolArea.unique()

array([  0, 144, 368, 444, 228, 561, 800], dtype=int64)

In [10]:
for area in df.PoolArea:
    if area!=0 and area<=566:
        df.PoolArea.replace(to_replace=area, value=1, inplace=True)
    elif area>566 and area<= 652:
        df.PoolArea.replace(to_replace=area, value=2, inplace=True)
    elif area >652:
        df.PoolArea.replace(to_replace=area, value=3, inplace=True)

In [11]:
df.PoolArea.unique()

array([0, 1, 3], dtype=int64)

In [12]:
df.Fence.replace(to_replace=[np.nan, 'MnPrv', 'GdWo', 'GdPrv', 'MnWw'], value=[0,3,2,4,1], inplace=True)
df.Fence.unique()

array([3, 0, 4, 2, 1], dtype=int64)

In [13]:
added_columns=pd.get_dummies(df.SaleCondition,prefix='SC')
added_columns.columns

Index(['SC_Abnorml', 'SC_AdjLand', 'SC_Alloca', 'SC_Family', 'SC_Normal',
       'SC_Partial'],
      dtype='object')

In [14]:
df.drop(columns='SaleCondition')
df['SC_Abnorml']=added_columns['SC_Abnorml']
df['SC_AdjLand']=added_columns['SC_AdjLand']
df['SC_Alloca']=added_columns['SC_Alloca']
df['SC_Family']=added_columns['SC_Family']
df['SC_Normal']=added_columns['SC_Normal']
df['SC_Partial']=added_columns['SC_Partial']

In [15]:
df.drop(columns=['SaleCondition'], inplace=True)
df.head()

Id  GarageCond  PavedDrive  WoodDeckSF  OpenPorchSF  EnclosedPorch  \
0  1461           3           2         140            0              0   
1  1462           3           2         393           36              0   
2  1463           3           2         212           34              0   
3  1464           3           2         360           36              0   
4  1465           3           2           0           82              0   

   3SsnPorch  ScreenPorch  PoolArea  Fence  MiscVal  SC_Abnorml  SC_AdjLand  \
0          0          120         0      3        0           0           0   
1          0            0         0      0    12500           0           0   
2          0            0         0      3        0           0           0   
3          0            0         0      0        0           0           0   
4          0          144         0      0        0           0           0   

   SC_Alloca  SC_Family  SC_Normal  SC_Partial  
0          0          0          1           0  
1          0          0          1           0  
2          0          0          1           0  
3          0          0          1           0  
4          0          0          1           0

In [16]:
df.to_csv('cleaned_BM_CB_text.csv')